-- MINERVA Database Schema
-- Run this in Supabase SQL Editor

-- Metrics time-series table
CREATE TABLE IF NOT EXISTS metrics_timeseries (
  id BIGSERIAL PRIMARY KEY,
  company_id TEXT NOT NULL,
  metric_type TEXT NOT NULL,
  value DECIMAL NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_metrics_company_type_time
ON metrics_timeseries(company_id, metric_type, timestamp);

-- Enable realtime for metrics
ALTER PUBLICATION supabase_realtime ADD TABLE metrics_timeseries;

-- Complaints table
CREATE TABLE IF NOT EXISTS complaints (
  id BIGSERIAL PRIMARY KEY,
  company_id TEXT NOT NULL,
  text TEXT NOT NULL,
  sentiment TEXT,
  sentiment_score DECIMAL,
  category TEXT,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  audio_url TEXT
);

CREATE INDEX IF NOT EXISTS idx_complaints_company_time
ON complaints(company_id, timestamp);

-- Brand profiles table
CREATE TABLE IF NOT EXISTS brand_profiles (
  id BIGSERIAL PRIMARY KEY,
  company_name TEXT UNIQUE NOT NULL,
  metrics JSONB NOT NULL DEFAULT '{}',
  last_updated TIMESTAMPTZ DEFAULT NOW()
);

-- Outage predictions table (for Sentinel feature)
CREATE TABLE IF NOT EXISTS outage_predictions (
  id BIGSERIAL PRIMARY KEY,
  company_id TEXT NOT NULL,
  risk_level TEXT NOT NULL,
  confidence DECIMAL NOT NULL,
  predicted_service TEXT,
  estimated_impact INTEGER,
  time_to_critical INTEGER,
  action_plan JSONB,
  similar_incident_id INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  resolved_at TIMESTAMPTZ,
  actual_outage BOOLEAN
);

CREATE INDEX IF NOT EXISTS idx_outage_predictions_company_time
ON outage_predictions(company_id, created_at);

-- SWOT analyses table
CREATE TABLE IF NOT EXISTS swot_analyses (
  id BIGSERIAL PRIMARY KEY,
  company_id TEXT NOT NULL,
  content JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Historical incidents table (for pattern matching)
CREATE TABLE IF NOT EXISTS historical_incidents (
  id BIGSERIAL PRIMARY KEY,
  company_id TEXT NOT NULL,
  incident_type TEXT NOT NULL,
  description TEXT,
  metrics_snapshot JSONB,
  resolution JSONB,
  occurred_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_historical_incidents_company
ON historical_incidents(company_id, occurred_at);

-- Comments
COMMENT ON TABLE metrics_timeseries IS 'Real-time metrics tracking (happiness, complaints velocity, etc.)';
COMMENT ON TABLE complaints IS 'Customer complaints with AI sentiment analysis';
COMMENT ON TABLE brand_profiles IS 'Company profile data and aggregate metrics';
COMMENT ON TABLE outage_predictions IS 'SENTINEL AI predictions for potential outages';
COMMENT ON TABLE swot_analyses IS 'SWOT analyses generated by AI';
COMMENT ON TABLE historical_incidents IS 'Past incidents for pattern matching';
